<?php

return [
    'SMK N 2 Surakarta' => [
        'Teknik Konstruksi dan Perumahan',
        'Desain Pemodelan & Informasi Bangunan',
        'Teknik Geomatika',
        'Teknik Elektronika',
        'Teknik Ketenagalistrikan',
        'Pemrograman Perangkat Lunak & GIM',
        'Teknik Jaringan Komputer & Telekomunikasi',
        'Teknik Otomotif',
        'Teknik Mesin',
        'Teknik Pengelasan & Fabrikasi Logam',
    ],
    'SMK N 5 Surakarta' => [
        'Desain Pemodelan dan Informasi Bangunan (DPIB)',
        'Teknik Konstruksi dan Perumahan (TKP)',
        'Teknik Mesin (TM)',
        'Teknik Kendaraan Ringan Otomotif (TKRO)',
        'Teknik dan Bisnis Sepeda Motor',
        'Teknik Elektronika Industri',
        'Teknik Ketenagalistrikan (TK)',
        'Teknik Otomasi Industri (TOI)',
        'Pengembangan Perangkat Lunak dan Gim (PPLG)',
    ],
    'SMK N 6 Surakarta' => [
        'Akuntansi Keuangan Lembaga',
        'Manajemen Perkantoran dan Layanan Bisnis',
        'Usaha Layanan Pariwisata',
        'Pemasaran',
        'Desain Komunikasi Visual',
        'Broadcasting dan Perfilman',
        'Rekayasa Perangkat Lunak',
    ],
    'SMK N 1 Sawit (Boyolali)' => [
        'Teknik Otomotif / Teknik Kendaraan Ringan (TKR)',
        'Teknik Komputer dan Jaringan (TKJ)',
        'Agribisnis Tanaman Pangan dan Hortikultura (ATPH)',
        'Agribisnis Pengolahan Hasil Pertanian (APHP)',
        'Akuntansi dan Keuangan Lembaga (AKL)',
    ],
    'SMK N 1 Banyudono (Boyolali)' => [
        'Teknik Jaringan dan Komputer',
        'Asisten Keperawatan',
        'Otomatisasi dan Kelola Perkantoran',
        'Akuntansi dan Keuangan Lembaga',
        'Bisnis Daring dan Pemasaran',
    ],
];
